DROP TABLE IF EXISTS [groups];
CREATE TABLE [groups] (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
name STRING UNIQUE
);

DROP TABLE IF EXISTS lectors;
CREATE TABLE lectors (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
full_name VARCHAR(30)
);

DROP TABLE IF EXISTS students;
CREATE TABLE students (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
full_name VARCHAR(30),
group_id REFERENCES [groups] (id)
);

DROP TABLE IF EXISTS subjects;
CREATE TABLE subjects (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
name STRING,
lector_id REFERENCES lectors (id)
);

DROP TABLE IF EXISTS marks;
CREATE TABLE marks (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
grade INTEGER,
date_getting DATE,
student_id REFERENCES students (id),
subject_name REFERENCES subjects (name)
);
